// Tests auto-generated by AI agent.
package avd_test

import (
	"testing"

	"github.com/facebookincubator/go-belt"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/avd/pkg/avd"
	"github.com/xaionaro-go/avd/pkg/management/grpc/proto/avdmanagementgrpc"
	"github.com/xaionaro-go/avpipeline/router"
)

// TestDeblemishGRPC_SetAndGet exercises the full gRPC round-trip:
// client → gRPC server → Backend (avd.Server) → DeblemishControl atomics → response.
func TestDeblemishGRPC_SetAndGet(t *testing.T) {
	ctx := testCtx()
	defer belt.Flush(ctx)

	srv := avd.NewServer(ctx)
	defer func() { _ = srv.Close(ctx) }()

	key := avd.DeblemishControlKey{
		RoutePath:       router.RoutePath("live/stream"),
		ForwardingIndex: 0,
	}
	ctrl := &avd.DeblemishControl{}
	srv.RegisterDeblemishControl(ctx, key, ctrl)

	addr := startGRPCServer(t, ctx, srv)
	grpcClient := newGRPCClient(t, ctx, addr)

	// 1. Get defaults.
	resp, err := grpcClient.GetDeblemish(ctx, &avdmanagementgrpc.GetDeblemishRequest{
		RoutePath:       "live/stream",
		ForwardingIndex: 0,
	})
	require.NoError(t, err)
	assert.False(t, resp.Enabled)
	assert.Equal(t, float64(0), resp.SigmaS)
	assert.Equal(t, float64(0), resp.SigmaR)
	assert.Equal(t, int64(0), resp.Diameter)

	// 2. Set all fields.
	enabled := true
	sigmaS := 15.0
	sigmaR := 0.2
	diameter := int64(5)
	_, err = grpcClient.SetDeblemish(ctx, &avdmanagementgrpc.SetDeblemishRequest{
		RoutePath:       "live/stream",
		ForwardingIndex: 0,
		Enabled:         &enabled,
		SigmaS:          &sigmaS,
		SigmaR:          &sigmaR,
		Diameter:        &diameter,
	})
	require.NoError(t, err)

	// 3. Verify via Get over gRPC.
	resp, err = grpcClient.GetDeblemish(ctx, &avdmanagementgrpc.GetDeblemishRequest{
		RoutePath:       "live/stream",
		ForwardingIndex: 0,
	})
	require.NoError(t, err)
	assert.True(t, resp.Enabled)
	assert.Equal(t, 15.0, resp.SigmaS)
	assert.Equal(t, 0.2, resp.SigmaR)
	assert.Equal(t, int64(5), resp.Diameter)

	// 4. Verify the underlying atomics were set via Server's exported method.
	gotEnabled, gotSigmaS, gotSigmaR, gotDiameter, err := srv.GetDeblemishState(ctx, key)
	require.NoError(t, err)
	assert.True(t, gotEnabled)
	assert.Equal(t, 15.0, gotSigmaS)
	assert.Equal(t, 0.2, gotSigmaR)
	assert.Equal(t, int64(5), gotDiameter)
}

// TestDeblemishGRPC_PartialUpdate verifies that setting only some fields
// leaves others unchanged.
func TestDeblemishGRPC_PartialUpdate(t *testing.T) {
	ctx := testCtx()
	defer belt.Flush(ctx)

	srv := avd.NewServer(ctx)
	defer func() { _ = srv.Close(ctx) }()

	key := avd.DeblemishControlKey{
		RoutePath:       router.RoutePath("live/cam"),
		ForwardingIndex: 1,
	}
	ctrl := &avd.DeblemishControl{}
	ctrl.Enabled.Store(true)
	ctrl.SetSigmaS(ctx, 10.0)
	ctrl.SetSigmaR(ctx, 0.1)
	ctrl.SetDiameter(ctx, -1)
	srv.RegisterDeblemishControl(ctx, key, ctrl)

	addr := startGRPCServer(t, ctx, srv)
	grpcClient := newGRPCClient(t, ctx, addr)

	// Update only sigma_s via gRPC.
	newSigmaS := 25.0
	_, err := grpcClient.SetDeblemish(ctx, &avdmanagementgrpc.SetDeblemishRequest{
		RoutePath:       "live/cam",
		ForwardingIndex: 1,
		SigmaS:          &newSigmaS,
	})
	require.NoError(t, err)

	// Verify: sigma_s changed, others untouched.
	resp, err := grpcClient.GetDeblemish(ctx, &avdmanagementgrpc.GetDeblemishRequest{
		RoutePath:       "live/cam",
		ForwardingIndex: 1,
	})
	require.NoError(t, err)
	assert.True(t, resp.Enabled, "Enabled should be unchanged")
	assert.Equal(t, 25.0, resp.SigmaS, "SigmaS should be updated")
	assert.Equal(t, 0.1, resp.SigmaR, "SigmaR should be unchanged")
	assert.Equal(t, int64(-1), resp.Diameter, "Diameter should be unchanged")
}

// TestDeblemishGRPC_NotFound verifies that accessing a non-registered route
// returns an error through the gRPC layer.
func TestDeblemishGRPC_NotFound(t *testing.T) {
	ctx := testCtx()
	defer belt.Flush(ctx)

	srv := avd.NewServer(ctx)
	defer func() { _ = srv.Close(ctx) }()

	addr := startGRPCServer(t, ctx, srv)
	grpcClient := newGRPCClient(t, ctx, addr)

	// Get on non-existent route.
	_, err := grpcClient.GetDeblemish(ctx, &avdmanagementgrpc.GetDeblemishRequest{
		RoutePath:       "nonexistent/stream",
		ForwardingIndex: 0,
	})
	assert.Error(t, err)

	// Set on non-existent route.
	enabled := true
	_, err = grpcClient.SetDeblemish(ctx, &avdmanagementgrpc.SetDeblemishRequest{
		RoutePath:       "nonexistent/stream",
		ForwardingIndex: 0,
		Enabled:         &enabled,
	})
	assert.Error(t, err)
}

// TestDeblemishGRPC_DisableToggle verifies enabling then disabling deblemish
// via gRPC round-trips correctly.
func TestDeblemishGRPC_DisableToggle(t *testing.T) {
	ctx := testCtx()
	defer belt.Flush(ctx)

	srv := avd.NewServer(ctx)
	defer func() { _ = srv.Close(ctx) }()

	key := avd.DeblemishControlKey{
		RoutePath:       router.RoutePath("toggle/test"),
		ForwardingIndex: 0,
	}
	ctrl := &avd.DeblemishControl{}
	srv.RegisterDeblemishControl(ctx, key, ctrl)

	addr := startGRPCServer(t, ctx, srv)
	grpcClient := newGRPCClient(t, ctx, addr)

	// Enable.
	enabled := true
	_, err := grpcClient.SetDeblemish(ctx, &avdmanagementgrpc.SetDeblemishRequest{
		RoutePath: "toggle/test",
		Enabled:   &enabled,
	})
	require.NoError(t, err)

	resp, err := grpcClient.GetDeblemish(ctx, &avdmanagementgrpc.GetDeblemishRequest{
		RoutePath: "toggle/test",
	})
	require.NoError(t, err)
	assert.True(t, resp.Enabled)

	// Disable.
	disabled := false
	_, err = grpcClient.SetDeblemish(ctx, &avdmanagementgrpc.SetDeblemishRequest{
		RoutePath: "toggle/test",
		Enabled:   &disabled,
	})
	require.NoError(t, err)

	resp, err = grpcClient.GetDeblemish(ctx, &avdmanagementgrpc.GetDeblemishRequest{
		RoutePath: "toggle/test",
	})
	require.NoError(t, err)
	assert.False(t, resp.Enabled)

	// Verify atomics directly.
	assert.False(t, ctrl.Enabled.Load())
}

// TestDeblemishGRPC_KernelPropagation verifies that SetDeblemishState
// propagates parameter changes to the live kernel's atomic fields.
func TestDeblemishGRPC_KernelPropagation(t *testing.T) {
	ctx := testCtx()
	defer belt.Flush(ctx)

	srv := avd.NewServer(ctx)
	defer func() { _ = srv.Close(ctx) }()

	key := avd.DeblemishControlKey{
		RoutePath:       router.RoutePath("propagation/test"),
		ForwardingIndex: 0,
	}
	ctrl := &avd.DeblemishControl{}
	ctrl.SetSigmaS(ctx, 10.0)
	ctrl.SetSigmaR(ctx, 0.1)
	srv.RegisterDeblemishControl(ctx, key, ctrl)

	addr := startGRPCServer(t, ctx, srv)
	grpcClient := newGRPCClient(t, ctx, addr)

	// Update via gRPC.
	sigmaS := 20.0
	sigmaR := 0.5
	_, err := grpcClient.SetDeblemish(ctx, &avdmanagementgrpc.SetDeblemishRequest{
		RoutePath:       "propagation/test",
		ForwardingIndex: 0,
		SigmaS:          &sigmaS,
		SigmaR:          &sigmaR,
	})
	require.NoError(t, err)

	// Verify the control's atomics are updated.
	assert.Equal(t, 20.0, ctrl.GetSigmaS())
	assert.Equal(t, 0.5, ctrl.GetSigmaR())
}
