// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: avd.proto

package avdmanagementgrpc

import (
	avpipeline "github.com/xaionaro-go/avpipeline/protobuf/avpipeline"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListPublishersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPublishersRequest) Reset() {
	*x = ListPublishersRequest{}
	mi := &file_avd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPublishersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublishersRequest) ProtoMessage() {}

func (x *ListPublishersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublishersRequest.ProtoReflect.Descriptor instead.
func (*ListPublishersRequest) Descriptor() ([]byte, []int) {
	return file_avd_proto_rawDescGZIP(), []int{0}
}

type ListPublishersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*avpipeline.Node     `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPublishersResponse) Reset() {
	*x = ListPublishersResponse{}
	mi := &file_avd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPublishersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublishersResponse) ProtoMessage() {}

func (x *ListPublishersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublishersResponse.ProtoReflect.Descriptor instead.
func (*ListPublishersResponse) Descriptor() ([]byte, []int) {
	return file_avd_proto_rawDescGZIP(), []int{1}
}

func (x *ListPublishersResponse) GetNodes() []*avpipeline.Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type ListRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutesRequest) Reset() {
	*x = ListRoutesRequest{}
	mi := &file_avd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesRequest) ProtoMessage() {}

func (x *ListRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesRequest.ProtoReflect.Descriptor instead.
func (*ListRoutesRequest) Descriptor() ([]byte, []int) {
	return file_avd_proto_rawDescGZIP(), []int{2}
}

type ListRoutesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*avpipeline.Node     `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	RoutePaths    []string               `protobuf:"bytes,2,rep,name=route_paths,json=routePaths,proto3" json:"route_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutesResponse) Reset() {
	*x = ListRoutesResponse{}
	mi := &file_avd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesResponse) ProtoMessage() {}

func (x *ListRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesResponse.ProtoReflect.Descriptor instead.
func (*ListRoutesResponse) Descriptor() ([]byte, []int) {
	return file_avd_proto_rawDescGZIP(), []int{3}
}

func (x *ListRoutesResponse) GetNodes() []*avpipeline.Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ListRoutesResponse) GetRoutePaths() []string {
	if x != nil {
		return x.RoutePaths
	}
	return nil
}

type ListConsumersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConsumersRequest) Reset() {
	*x = ListConsumersRequest{}
	mi := &file_avd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsumersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsumersRequest) ProtoMessage() {}

func (x *ListConsumersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsumersRequest.ProtoReflect.Descriptor instead.
func (*ListConsumersRequest) Descriptor() ([]byte, []int) {
	return file_avd_proto_rawDescGZIP(), []int{4}
}

type ListConsumersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*avpipeline.Node     `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConsumersResponse) Reset() {
	*x = ListConsumersResponse{}
	mi := &file_avd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConsumersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConsumersResponse) ProtoMessage() {}

func (x *ListConsumersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConsumersResponse.ProtoReflect.Descriptor instead.
func (*ListConsumersResponse) Descriptor() ([]byte, []int) {
	return file_avd_proto_rawDescGZIP(), []int{5}
}

func (x *ListConsumersResponse) GetNodes() []*avpipeline.Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type SetPrivacyBlurRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RoutePath         string                 `protobuf:"bytes,1,opt,name=route_path,json=routePath,proto3" json:"route_path,omitempty"`
	ForwardingIndex   int32                  `protobuf:"varint,2,opt,name=forwarding_index,json=forwardingIndex,proto3" json:"forwarding_index,omitempty"`
	Enabled           *bool                  `protobuf:"varint,3,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	BlurRadius        *float64               `protobuf:"fixed64,4,opt,name=blur_radius,json=blurRadius,proto3,oneof" json:"blur_radius,omitempty"`
	PixelateBlockSize *int64                 `protobuf:"varint,5,opt,name=pixelate_block_size,json=pixelateBlockSize,proto3,oneof" json:"pixelate_block_size,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SetPrivacyBlurRequest) Reset() {
	*x = SetPrivacyBlurRequest{}
	mi := &file_avd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPrivacyBlurRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPrivacyBlurRequest) ProtoMessage() {}

func (x *SetPrivacyBlurRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPrivacyBlurRequest.ProtoReflect.Descriptor instead.
func (*SetPrivacyBlurRequest) Descriptor() ([]byte, []int) {
	return file_avd_proto_rawDescGZIP(), []int{6}
}

func (x *SetPrivacyBlurRequest) GetRoutePath() string {
	if x != nil {
		return x.RoutePath
	}
	return ""
}

func (x *SetPrivacyBlurRequest) GetForwardingIndex() int32 {
	if x != nil {
		return x.ForwardingIndex
	}
	return 0
}

func (x *SetPrivacyBlurRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *SetPrivacyBlurRequest) GetBlurRadius() float64 {
	if x != nil && x.BlurRadius != nil {
		return *x.BlurRadius
	}
	return 0
}

func (x *SetPrivacyBlurRequest) GetPixelateBlockSize() int64 {
	if x != nil && x.PixelateBlockSize != nil {
		return *x.PixelateBlockSize
	}
	return 0
}

type SetPrivacyBlurResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPrivacyBlurResponse) Reset() {
	*x = SetPrivacyBlurResponse{}
	mi := &file_avd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPrivacyBlurResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPrivacyBlurResponse) ProtoMessage() {}

func (x *SetPrivacyBlurResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPrivacyBlurResponse.ProtoReflect.Descriptor instead.
func (*SetPrivacyBlurResponse) Descriptor() ([]byte, []int) {
	return file_avd_proto_rawDescGZIP(), []int{7}
}

type GetPrivacyBlurRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoutePath       string                 `protobuf:"bytes,1,opt,name=route_path,json=routePath,proto3" json:"route_path,omitempty"`
	ForwardingIndex int32                  `protobuf:"varint,2,opt,name=forwarding_index,json=forwardingIndex,proto3" json:"forwarding_index,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetPrivacyBlurRequest) Reset() {
	*x = GetPrivacyBlurRequest{}
	mi := &file_avd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrivacyBlurRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivacyBlurRequest) ProtoMessage() {}

func (x *GetPrivacyBlurRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivacyBlurRequest.ProtoReflect.Descriptor instead.
func (*GetPrivacyBlurRequest) Descriptor() ([]byte, []int) {
	return file_avd_proto_rawDescGZIP(), []int{8}
}

func (x *GetPrivacyBlurRequest) GetRoutePath() string {
	if x != nil {
		return x.RoutePath
	}
	return ""
}

func (x *GetPrivacyBlurRequest) GetForwardingIndex() int32 {
	if x != nil {
		return x.ForwardingIndex
	}
	return 0
}

type GetPrivacyBlurResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Enabled           bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	BlurRadius        float64                `protobuf:"fixed64,2,opt,name=blur_radius,json=blurRadius,proto3" json:"blur_radius,omitempty"`
	PixelateBlockSize int64                  `protobuf:"varint,3,opt,name=pixelate_block_size,json=pixelateBlockSize,proto3" json:"pixelate_block_size,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetPrivacyBlurResponse) Reset() {
	*x = GetPrivacyBlurResponse{}
	mi := &file_avd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrivacyBlurResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivacyBlurResponse) ProtoMessage() {}

func (x *GetPrivacyBlurResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivacyBlurResponse.ProtoReflect.Descriptor instead.
func (*GetPrivacyBlurResponse) Descriptor() ([]byte, []int) {
	return file_avd_proto_rawDescGZIP(), []int{9}
}

func (x *GetPrivacyBlurResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *GetPrivacyBlurResponse) GetBlurRadius() float64 {
	if x != nil {
		return x.BlurRadius
	}
	return 0
}

func (x *GetPrivacyBlurResponse) GetPixelateBlockSize() int64 {
	if x != nil {
		return x.PixelateBlockSize
	}
	return 0
}

type SetDeblemishRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoutePath       string                 `protobuf:"bytes,1,opt,name=route_path,json=routePath,proto3" json:"route_path,omitempty"`
	ForwardingIndex int32                  `protobuf:"varint,2,opt,name=forwarding_index,json=forwardingIndex,proto3" json:"forwarding_index,omitempty"`
	Enabled         *bool                  `protobuf:"varint,3,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	SigmaS          *float64               `protobuf:"fixed64,4,opt,name=sigma_s,json=sigmaS,proto3,oneof" json:"sigma_s,omitempty"`
	SigmaR          *float64               `protobuf:"fixed64,5,opt,name=sigma_r,json=sigmaR,proto3,oneof" json:"sigma_r,omitempty"`
	Diameter        *int64                 `protobuf:"varint,6,opt,name=diameter,proto3,oneof" json:"diameter,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetDeblemishRequest) Reset() {
	*x = SetDeblemishRequest{}
	mi := &file_avd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDeblemishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeblemishRequest) ProtoMessage() {}

func (x *SetDeblemishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeblemishRequest.ProtoReflect.Descriptor instead.
func (*SetDeblemishRequest) Descriptor() ([]byte, []int) {
	return file_avd_proto_rawDescGZIP(), []int{10}
}

func (x *SetDeblemishRequest) GetRoutePath() string {
	if x != nil {
		return x.RoutePath
	}
	return ""
}

func (x *SetDeblemishRequest) GetForwardingIndex() int32 {
	if x != nil {
		return x.ForwardingIndex
	}
	return 0
}

func (x *SetDeblemishRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *SetDeblemishRequest) GetSigmaS() float64 {
	if x != nil && x.SigmaS != nil {
		return *x.SigmaS
	}
	return 0
}

func (x *SetDeblemishRequest) GetSigmaR() float64 {
	if x != nil && x.SigmaR != nil {
		return *x.SigmaR
	}
	return 0
}

func (x *SetDeblemishRequest) GetDiameter() int64 {
	if x != nil && x.Diameter != nil {
		return *x.Diameter
	}
	return 0
}

type SetDeblemishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDeblemishResponse) Reset() {
	*x = SetDeblemishResponse{}
	mi := &file_avd_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDeblemishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeblemishResponse) ProtoMessage() {}

func (x *SetDeblemishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avd_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeblemishResponse.ProtoReflect.Descriptor instead.
func (*SetDeblemishResponse) Descriptor() ([]byte, []int) {
	return file_avd_proto_rawDescGZIP(), []int{11}
}

type GetDeblemishRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoutePath       string                 `protobuf:"bytes,1,opt,name=route_path,json=routePath,proto3" json:"route_path,omitempty"`
	ForwardingIndex int32                  `protobuf:"varint,2,opt,name=forwarding_index,json=forwardingIndex,proto3" json:"forwarding_index,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetDeblemishRequest) Reset() {
	*x = GetDeblemishRequest{}
	mi := &file_avd_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeblemishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeblemishRequest) ProtoMessage() {}

func (x *GetDeblemishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avd_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeblemishRequest.ProtoReflect.Descriptor instead.
func (*GetDeblemishRequest) Descriptor() ([]byte, []int) {
	return file_avd_proto_rawDescGZIP(), []int{12}
}

func (x *GetDeblemishRequest) GetRoutePath() string {
	if x != nil {
		return x.RoutePath
	}
	return ""
}

func (x *GetDeblemishRequest) GetForwardingIndex() int32 {
	if x != nil {
		return x.ForwardingIndex
	}
	return 0
}

type GetDeblemishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	SigmaS        float64                `protobuf:"fixed64,2,opt,name=sigma_s,json=sigmaS,proto3" json:"sigma_s,omitempty"`
	SigmaR        float64                `protobuf:"fixed64,3,opt,name=sigma_r,json=sigmaR,proto3" json:"sigma_r,omitempty"`
	Diameter      int64                  `protobuf:"varint,4,opt,name=diameter,proto3" json:"diameter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeblemishResponse) Reset() {
	*x = GetDeblemishResponse{}
	mi := &file_avd_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeblemishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeblemishResponse) ProtoMessage() {}

func (x *GetDeblemishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avd_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeblemishResponse.ProtoReflect.Descriptor instead.
func (*GetDeblemishResponse) Descriptor() ([]byte, []int) {
	return file_avd_proto_rawDescGZIP(), []int{13}
}

func (x *GetDeblemishResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *GetDeblemishResponse) GetSigmaS() float64 {
	if x != nil {
		return x.SigmaS
	}
	return 0
}

func (x *GetDeblemishResponse) GetSigmaR() float64 {
	if x != nil {
		return x.SigmaR
	}
	return 0
}

func (x *GetDeblemishResponse) GetDiameter() int64 {
	if x != nil {
		return x.Diameter
	}
	return 0
}

type FilterControlInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoutePath       string                 `protobuf:"bytes,1,opt,name=route_path,json=routePath,proto3" json:"route_path,omitempty"`
	ForwardingIndex int32                  `protobuf:"varint,2,opt,name=forwarding_index,json=forwardingIndex,proto3" json:"forwarding_index,omitempty"`
	HasPrivacyBlur  bool                   `protobuf:"varint,3,opt,name=has_privacy_blur,json=hasPrivacyBlur,proto3" json:"has_privacy_blur,omitempty"`
	HasDeblemish    bool                   `protobuf:"varint,4,opt,name=has_deblemish,json=hasDeblemish,proto3" json:"has_deblemish,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FilterControlInfo) Reset() {
	*x = FilterControlInfo{}
	mi := &file_avd_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterControlInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterControlInfo) ProtoMessage() {}

func (x *FilterControlInfo) ProtoReflect() protoreflect.Message {
	mi := &file_avd_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterControlInfo.ProtoReflect.Descriptor instead.
func (*FilterControlInfo) Descriptor() ([]byte, []int) {
	return file_avd_proto_rawDescGZIP(), []int{14}
}

func (x *FilterControlInfo) GetRoutePath() string {
	if x != nil {
		return x.RoutePath
	}
	return ""
}

func (x *FilterControlInfo) GetForwardingIndex() int32 {
	if x != nil {
		return x.ForwardingIndex
	}
	return 0
}

func (x *FilterControlInfo) GetHasPrivacyBlur() bool {
	if x != nil {
		return x.HasPrivacyBlur
	}
	return false
}

func (x *FilterControlInfo) GetHasDeblemish() bool {
	if x != nil {
		return x.HasDeblemish
	}
	return false
}

type ListFilterControlsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilterControlsRequest) Reset() {
	*x = ListFilterControlsRequest{}
	mi := &file_avd_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilterControlsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilterControlsRequest) ProtoMessage() {}

func (x *ListFilterControlsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avd_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilterControlsRequest.ProtoReflect.Descriptor instead.
func (*ListFilterControlsRequest) Descriptor() ([]byte, []int) {
	return file_avd_proto_rawDescGZIP(), []int{15}
}

type ListFilterControlsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Controls      []*FilterControlInfo   `protobuf:"bytes,1,rep,name=controls,proto3" json:"controls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilterControlsResponse) Reset() {
	*x = ListFilterControlsResponse{}
	mi := &file_avd_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilterControlsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilterControlsResponse) ProtoMessage() {}

func (x *ListFilterControlsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avd_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilterControlsResponse.ProtoReflect.Descriptor instead.
func (*ListFilterControlsResponse) Descriptor() ([]byte, []int) {
	return file_avd_proto_rawDescGZIP(), []int{16}
}

func (x *ListFilterControlsResponse) GetControls() []*FilterControlInfo {
	if x != nil {
		return x.Controls
	}
	return nil
}

type ActivateRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoutePath     string                 `protobuf:"bytes,1,opt,name=route_path,json=routePath,proto3" json:"route_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateRouteRequest) Reset() {
	*x = ActivateRouteRequest{}
	mi := &file_avd_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateRouteRequest) ProtoMessage() {}

func (x *ActivateRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avd_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateRouteRequest.ProtoReflect.Descriptor instead.
func (*ActivateRouteRequest) Descriptor() ([]byte, []int) {
	return file_avd_proto_rawDescGZIP(), []int{17}
}

func (x *ActivateRouteRequest) GetRoutePath() string {
	if x != nil {
		return x.RoutePath
	}
	return ""
}

type ActivateRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateRouteResponse) Reset() {
	*x = ActivateRouteResponse{}
	mi := &file_avd_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateRouteResponse) ProtoMessage() {}

func (x *ActivateRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avd_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateRouteResponse.ProtoReflect.Descriptor instead.
func (*ActivateRouteResponse) Descriptor() ([]byte, []int) {
	return file_avd_proto_rawDescGZIP(), []int{18}
}

type DeactivateRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoutePath     string                 `protobuf:"bytes,1,opt,name=route_path,json=routePath,proto3" json:"route_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateRouteRequest) Reset() {
	*x = DeactivateRouteRequest{}
	mi := &file_avd_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateRouteRequest) ProtoMessage() {}

func (x *DeactivateRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_avd_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateRouteRequest.ProtoReflect.Descriptor instead.
func (*DeactivateRouteRequest) Descriptor() ([]byte, []int) {
	return file_avd_proto_rawDescGZIP(), []int{19}
}

func (x *DeactivateRouteRequest) GetRoutePath() string {
	if x != nil {
		return x.RoutePath
	}
	return ""
}

type DeactivateRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateRouteResponse) Reset() {
	*x = DeactivateRouteResponse{}
	mi := &file_avd_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateRouteResponse) ProtoMessage() {}

func (x *DeactivateRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_avd_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateRouteResponse.ProtoReflect.Descriptor instead.
func (*DeactivateRouteResponse) Descriptor() ([]byte, []int) {
	return file_avd_proto_rawDescGZIP(), []int{20}
}

var File_avd_proto protoreflect.FileDescriptor

const file_avd_proto_rawDesc = "" +
	"\n" +
	"\tavd.proto\x1a,imports/avpipeline/protobuf/avpipeline.proto\"\x17\n" +
	"\x15ListPublishersRequest\"@\n" +
	"\x16ListPublishersResponse\x12&\n" +
	"\x05nodes\x18\x01 \x03(\v2\x10.avpipeline.NodeR\x05nodes\"\x13\n" +
	"\x11ListRoutesRequest\"]\n" +
	"\x12ListRoutesResponse\x12&\n" +
	"\x05nodes\x18\x01 \x03(\v2\x10.avpipeline.NodeR\x05nodes\x12\x1f\n" +
	"\vroute_paths\x18\x02 \x03(\tR\n" +
	"routePaths\"\x16\n" +
	"\x14ListConsumersRequest\"?\n" +
	"\x15ListConsumersResponse\x12&\n" +
	"\x05nodes\x18\x01 \x03(\v2\x10.avpipeline.NodeR\x05nodes\"\x8f\x02\n" +
	"\x15SetPrivacyBlurRequest\x12\x1d\n" +
	"\n" +
	"route_path\x18\x01 \x01(\tR\troutePath\x12)\n" +
	"\x10forwarding_index\x18\x02 \x01(\x05R\x0fforwardingIndex\x12\x1d\n" +
	"\aenabled\x18\x03 \x01(\bH\x00R\aenabled\x88\x01\x01\x12$\n" +
	"\vblur_radius\x18\x04 \x01(\x01H\x01R\n" +
	"blurRadius\x88\x01\x01\x123\n" +
	"\x13pixelate_block_size\x18\x05 \x01(\x03H\x02R\x11pixelateBlockSize\x88\x01\x01B\n" +
	"\n" +
	"\b_enabledB\x0e\n" +
	"\f_blur_radiusB\x16\n" +
	"\x14_pixelate_block_size\"\x18\n" +
	"\x16SetPrivacyBlurResponse\"a\n" +
	"\x15GetPrivacyBlurRequest\x12\x1d\n" +
	"\n" +
	"route_path\x18\x01 \x01(\tR\troutePath\x12)\n" +
	"\x10forwarding_index\x18\x02 \x01(\x05R\x0fforwardingIndex\"\x83\x01\n" +
	"\x16GetPrivacyBlurResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1f\n" +
	"\vblur_radius\x18\x02 \x01(\x01R\n" +
	"blurRadius\x12.\n" +
	"\x13pixelate_block_size\x18\x03 \x01(\x03R\x11pixelateBlockSize\"\x8c\x02\n" +
	"\x13SetDeblemishRequest\x12\x1d\n" +
	"\n" +
	"route_path\x18\x01 \x01(\tR\troutePath\x12)\n" +
	"\x10forwarding_index\x18\x02 \x01(\x05R\x0fforwardingIndex\x12\x1d\n" +
	"\aenabled\x18\x03 \x01(\bH\x00R\aenabled\x88\x01\x01\x12\x1c\n" +
	"\asigma_s\x18\x04 \x01(\x01H\x01R\x06sigmaS\x88\x01\x01\x12\x1c\n" +
	"\asigma_r\x18\x05 \x01(\x01H\x02R\x06sigmaR\x88\x01\x01\x12\x1f\n" +
	"\bdiameter\x18\x06 \x01(\x03H\x03R\bdiameter\x88\x01\x01B\n" +
	"\n" +
	"\b_enabledB\n" +
	"\n" +
	"\b_sigma_sB\n" +
	"\n" +
	"\b_sigma_rB\v\n" +
	"\t_diameter\"\x16\n" +
	"\x14SetDeblemishResponse\"_\n" +
	"\x13GetDeblemishRequest\x12\x1d\n" +
	"\n" +
	"route_path\x18\x01 \x01(\tR\troutePath\x12)\n" +
	"\x10forwarding_index\x18\x02 \x01(\x05R\x0fforwardingIndex\"~\n" +
	"\x14GetDeblemishResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x17\n" +
	"\asigma_s\x18\x02 \x01(\x01R\x06sigmaS\x12\x17\n" +
	"\asigma_r\x18\x03 \x01(\x01R\x06sigmaR\x12\x1a\n" +
	"\bdiameter\x18\x04 \x01(\x03R\bdiameter\"\xac\x01\n" +
	"\x11FilterControlInfo\x12\x1d\n" +
	"\n" +
	"route_path\x18\x01 \x01(\tR\troutePath\x12)\n" +
	"\x10forwarding_index\x18\x02 \x01(\x05R\x0fforwardingIndex\x12(\n" +
	"\x10has_privacy_blur\x18\x03 \x01(\bR\x0ehasPrivacyBlur\x12#\n" +
	"\rhas_deblemish\x18\x04 \x01(\bR\fhasDeblemish\"\x1b\n" +
	"\x19ListFilterControlsRequest\"L\n" +
	"\x1aListFilterControlsResponse\x12.\n" +
	"\bcontrols\x18\x01 \x03(\v2\x12.FilterControlInfoR\bcontrols\"5\n" +
	"\x14ActivateRouteRequest\x12\x1d\n" +
	"\n" +
	"route_path\x18\x01 \x01(\tR\troutePath\"\x17\n" +
	"\x15ActivateRouteResponse\"7\n" +
	"\x16DeactivateRouteRequest\x12\x1d\n" +
	"\n" +
	"route_path\x18\x01 \x01(\tR\troutePath\"\x19\n" +
	"\x17DeactivateRouteResponse2\xde\x05\n" +
	"\n" +
	"AvdService\x12A\n" +
	"\x0eListPublishers\x12\x16.ListPublishersRequest\x1a\x17.ListPublishersResponse\x125\n" +
	"\n" +
	"ListRoutes\x12\x12.ListRoutesRequest\x1a\x13.ListRoutesResponse\x12>\n" +
	"\rListConsumers\x12\x15.ListConsumersRequest\x1a\x16.ListConsumersResponse\x12A\n" +
	"\aMonitor\x12\x1a.avpipeline.MonitorRequest\x1a\x18.avpipeline.MonitorEvent0\x01\x12A\n" +
	"\x0eSetPrivacyBlur\x12\x16.SetPrivacyBlurRequest\x1a\x17.SetPrivacyBlurResponse\x12A\n" +
	"\x0eGetPrivacyBlur\x12\x16.GetPrivacyBlurRequest\x1a\x17.GetPrivacyBlurResponse\x12;\n" +
	"\fSetDeblemish\x12\x14.SetDeblemishRequest\x1a\x15.SetDeblemishResponse\x12;\n" +
	"\fGetDeblemish\x12\x14.GetDeblemishRequest\x1a\x15.GetDeblemishResponse\x12M\n" +
	"\x12ListFilterControls\x12\x1a.ListFilterControlsRequest\x1a\x1b.ListFilterControlsResponse\x12>\n" +
	"\rActivateRoute\x12\x15.ActivateRouteRequest\x1a\x16.ActivateRouteResponse\x12D\n" +
	"\x0fDeactivateRoute\x12\x17.DeactivateRouteRequest\x1a\x18.DeactivateRouteResponseBHZFgithub.com/xaionaro-go/avd/pkg/management/grpc/proto;avdmanagementgrpcb\x06proto3"

var (
	file_avd_proto_rawDescOnce sync.Once
	file_avd_proto_rawDescData []byte
)

func file_avd_proto_rawDescGZIP() []byte {
	file_avd_proto_rawDescOnce.Do(func() {
		file_avd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_avd_proto_rawDesc), len(file_avd_proto_rawDesc)))
	})
	return file_avd_proto_rawDescData
}

var file_avd_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_avd_proto_goTypes = []any{
	(*ListPublishersRequest)(nil),      // 0: ListPublishersRequest
	(*ListPublishersResponse)(nil),     // 1: ListPublishersResponse
	(*ListRoutesRequest)(nil),          // 2: ListRoutesRequest
	(*ListRoutesResponse)(nil),         // 3: ListRoutesResponse
	(*ListConsumersRequest)(nil),       // 4: ListConsumersRequest
	(*ListConsumersResponse)(nil),      // 5: ListConsumersResponse
	(*SetPrivacyBlurRequest)(nil),      // 6: SetPrivacyBlurRequest
	(*SetPrivacyBlurResponse)(nil),     // 7: SetPrivacyBlurResponse
	(*GetPrivacyBlurRequest)(nil),      // 8: GetPrivacyBlurRequest
	(*GetPrivacyBlurResponse)(nil),     // 9: GetPrivacyBlurResponse
	(*SetDeblemishRequest)(nil),        // 10: SetDeblemishRequest
	(*SetDeblemishResponse)(nil),       // 11: SetDeblemishResponse
	(*GetDeblemishRequest)(nil),        // 12: GetDeblemishRequest
	(*GetDeblemishResponse)(nil),       // 13: GetDeblemishResponse
	(*FilterControlInfo)(nil),          // 14: FilterControlInfo
	(*ListFilterControlsRequest)(nil),  // 15: ListFilterControlsRequest
	(*ListFilterControlsResponse)(nil), // 16: ListFilterControlsResponse
	(*ActivateRouteRequest)(nil),       // 17: ActivateRouteRequest
	(*ActivateRouteResponse)(nil),      // 18: ActivateRouteResponse
	(*DeactivateRouteRequest)(nil),     // 19: DeactivateRouteRequest
	(*DeactivateRouteResponse)(nil),    // 20: DeactivateRouteResponse
	(*avpipeline.Node)(nil),            // 21: avpipeline.Node
	(*avpipeline.MonitorRequest)(nil),  // 22: avpipeline.MonitorRequest
	(*avpipeline.MonitorEvent)(nil),    // 23: avpipeline.MonitorEvent
}
var file_avd_proto_depIdxs = []int32{
	21, // 0: ListPublishersResponse.nodes:type_name -> avpipeline.Node
	21, // 1: ListRoutesResponse.nodes:type_name -> avpipeline.Node
	21, // 2: ListConsumersResponse.nodes:type_name -> avpipeline.Node
	14, // 3: ListFilterControlsResponse.controls:type_name -> FilterControlInfo
	0,  // 4: AvdService.ListPublishers:input_type -> ListPublishersRequest
	2,  // 5: AvdService.ListRoutes:input_type -> ListRoutesRequest
	4,  // 6: AvdService.ListConsumers:input_type -> ListConsumersRequest
	22, // 7: AvdService.Monitor:input_type -> avpipeline.MonitorRequest
	6,  // 8: AvdService.SetPrivacyBlur:input_type -> SetPrivacyBlurRequest
	8,  // 9: AvdService.GetPrivacyBlur:input_type -> GetPrivacyBlurRequest
	10, // 10: AvdService.SetDeblemish:input_type -> SetDeblemishRequest
	12, // 11: AvdService.GetDeblemish:input_type -> GetDeblemishRequest
	15, // 12: AvdService.ListFilterControls:input_type -> ListFilterControlsRequest
	17, // 13: AvdService.ActivateRoute:input_type -> ActivateRouteRequest
	19, // 14: AvdService.DeactivateRoute:input_type -> DeactivateRouteRequest
	1,  // 15: AvdService.ListPublishers:output_type -> ListPublishersResponse
	3,  // 16: AvdService.ListRoutes:output_type -> ListRoutesResponse
	5,  // 17: AvdService.ListConsumers:output_type -> ListConsumersResponse
	23, // 18: AvdService.Monitor:output_type -> avpipeline.MonitorEvent
	7,  // 19: AvdService.SetPrivacyBlur:output_type -> SetPrivacyBlurResponse
	9,  // 20: AvdService.GetPrivacyBlur:output_type -> GetPrivacyBlurResponse
	11, // 21: AvdService.SetDeblemish:output_type -> SetDeblemishResponse
	13, // 22: AvdService.GetDeblemish:output_type -> GetDeblemishResponse
	16, // 23: AvdService.ListFilterControls:output_type -> ListFilterControlsResponse
	18, // 24: AvdService.ActivateRoute:output_type -> ActivateRouteResponse
	20, // 25: AvdService.DeactivateRoute:output_type -> DeactivateRouteResponse
	15, // [15:26] is the sub-list for method output_type
	4,  // [4:15] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_avd_proto_init() }
func file_avd_proto_init() {
	if File_avd_proto != nil {
		return
	}
	file_avd_proto_msgTypes[6].OneofWrappers = []any{}
	file_avd_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_avd_proto_rawDesc), len(file_avd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_avd_proto_goTypes,
		DependencyIndexes: file_avd_proto_depIdxs,
		MessageInfos:      file_avd_proto_msgTypes,
	}.Build()
	File_avd_proto = out.File
	file_avd_proto_goTypes = nil
	file_avd_proto_depIdxs = nil
}
