// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: avd.proto

package avdmanagementgrpc

import (
	context "context"
	avpipeline "github.com/xaionaro-go/avpipeline/protobuf/avpipeline"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	AvdService_ListPublishers_FullMethodName = "/AvdService/ListPublishers"
	AvdService_ListRoutes_FullMethodName     = "/AvdService/ListRoutes"
	AvdService_ListConsumers_FullMethodName  = "/AvdService/ListConsumers"
	AvdService_Monitor_FullMethodName        = "/AvdService/Monitor"
)

// AvdServiceClient is the client API for AvdService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AvdServiceClient interface {
	ListPublishers(ctx context.Context, in *ListPublishersRequest, opts ...grpc.CallOption) (*ListPublishersResponse, error)
	ListRoutes(ctx context.Context, in *ListRoutesRequest, opts ...grpc.CallOption) (*ListRoutesResponse, error)
	ListConsumers(ctx context.Context, in *ListConsumersRequest, opts ...grpc.CallOption) (*ListConsumersResponse, error)
	Monitor(ctx context.Context, in *avpipeline.MonitorRequest, opts ...grpc.CallOption) (AvdService_MonitorClient, error)
}

type avdServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAvdServiceClient(cc grpc.ClientConnInterface) AvdServiceClient {
	return &avdServiceClient{cc}
}

func (c *avdServiceClient) ListPublishers(ctx context.Context, in *ListPublishersRequest, opts ...grpc.CallOption) (*ListPublishersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPublishersResponse)
	err := c.cc.Invoke(ctx, AvdService_ListPublishers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avdServiceClient) ListRoutes(ctx context.Context, in *ListRoutesRequest, opts ...grpc.CallOption) (*ListRoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoutesResponse)
	err := c.cc.Invoke(ctx, AvdService_ListRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avdServiceClient) ListConsumers(ctx context.Context, in *ListConsumersRequest, opts ...grpc.CallOption) (*ListConsumersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConsumersResponse)
	err := c.cc.Invoke(ctx, AvdService_ListConsumers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avdServiceClient) Monitor(ctx context.Context, in *avpipeline.MonitorRequest, opts ...grpc.CallOption) (AvdService_MonitorClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AvdService_ServiceDesc.Streams[0], AvdService_Monitor_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &avdServiceMonitorClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AvdService_MonitorClient interface {
	Recv() (*avpipeline.MonitorEvent, error)
	grpc.ClientStream
}

type avdServiceMonitorClient struct {
	grpc.ClientStream
}

func (x *avdServiceMonitorClient) Recv() (*avpipeline.MonitorEvent, error) {
	m := new(avpipeline.MonitorEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AvdServiceServer is the server API for AvdService service.
// All implementations must embed UnimplementedAvdServiceServer
// for forward compatibility
type AvdServiceServer interface {
	ListPublishers(context.Context, *ListPublishersRequest) (*ListPublishersResponse, error)
	ListRoutes(context.Context, *ListRoutesRequest) (*ListRoutesResponse, error)
	ListConsumers(context.Context, *ListConsumersRequest) (*ListConsumersResponse, error)
	Monitor(*avpipeline.MonitorRequest, AvdService_MonitorServer) error
	mustEmbedUnimplementedAvdServiceServer()
}

// UnimplementedAvdServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAvdServiceServer struct {
}

func (UnimplementedAvdServiceServer) ListPublishers(context.Context, *ListPublishersRequest) (*ListPublishersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPublishers not implemented")
}
func (UnimplementedAvdServiceServer) ListRoutes(context.Context, *ListRoutesRequest) (*ListRoutesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRoutes not implemented")
}
func (UnimplementedAvdServiceServer) ListConsumers(context.Context, *ListConsumersRequest) (*ListConsumersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConsumers not implemented")
}
func (UnimplementedAvdServiceServer) Monitor(*avpipeline.MonitorRequest, AvdService_MonitorServer) error {
	return status.Errorf(codes.Unimplemented, "method Monitor not implemented")
}
func (UnimplementedAvdServiceServer) mustEmbedUnimplementedAvdServiceServer() {}

// UnsafeAvdServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AvdServiceServer will
// result in compilation errors.
type UnsafeAvdServiceServer interface {
	mustEmbedUnimplementedAvdServiceServer()
}

func RegisterAvdServiceServer(s grpc.ServiceRegistrar, srv AvdServiceServer) {
	s.RegisterService(&AvdService_ServiceDesc, srv)
}

func _AvdService_ListPublishers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPublishersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvdServiceServer).ListPublishers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AvdService_ListPublishers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvdServiceServer).ListPublishers(ctx, req.(*ListPublishersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AvdService_ListRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvdServiceServer).ListRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AvdService_ListRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvdServiceServer).ListRoutes(ctx, req.(*ListRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AvdService_ListConsumers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConsumersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvdServiceServer).ListConsumers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AvdService_ListConsumers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvdServiceServer).ListConsumers(ctx, req.(*ListConsumersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AvdService_Monitor_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(avpipeline.MonitorRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AvdServiceServer).Monitor(m, &avdServiceMonitorServer{ServerStream: stream})
}

type AvdService_MonitorServer interface {
	Send(*avpipeline.MonitorEvent) error
	grpc.ServerStream
}

type avdServiceMonitorServer struct {
	grpc.ServerStream
}

func (x *avdServiceMonitorServer) Send(m *avpipeline.MonitorEvent) error {
	return x.ServerStream.SendMsg(m)
}

// AvdService_ServiceDesc is the grpc.ServiceDesc for AvdService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AvdService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AvdService",
	HandlerType: (*AvdServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPublishers",
			Handler:    _AvdService_ListPublishers_Handler,
		},
		{
			MethodName: "ListRoutes",
			Handler:    _AvdService_ListRoutes_Handler,
		},
		{
			MethodName: "ListConsumers",
			Handler:    _AvdService_ListConsumers_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Monitor",
			Handler:       _AvdService_Monitor_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "avd.proto",
}
