// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: avd.proto

package avdmanagementgrpc

import (
	context "context"
	avpipeline "github.com/xaionaro-go/avpipeline/protobuf/avpipeline"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AvdService_ListPublishers_FullMethodName     = "/AvdService/ListPublishers"
	AvdService_ListRoutes_FullMethodName         = "/AvdService/ListRoutes"
	AvdService_ListConsumers_FullMethodName      = "/AvdService/ListConsumers"
	AvdService_Monitor_FullMethodName            = "/AvdService/Monitor"
	AvdService_SetPrivacyBlur_FullMethodName     = "/AvdService/SetPrivacyBlur"
	AvdService_GetPrivacyBlur_FullMethodName     = "/AvdService/GetPrivacyBlur"
	AvdService_SetDeblemish_FullMethodName       = "/AvdService/SetDeblemish"
	AvdService_GetDeblemish_FullMethodName       = "/AvdService/GetDeblemish"
	AvdService_ListFilterControls_FullMethodName = "/AvdService/ListFilterControls"
)

// AvdServiceClient is the client API for AvdService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AvdServiceClient interface {
	ListPublishers(ctx context.Context, in *ListPublishersRequest, opts ...grpc.CallOption) (*ListPublishersResponse, error)
	ListRoutes(ctx context.Context, in *ListRoutesRequest, opts ...grpc.CallOption) (*ListRoutesResponse, error)
	ListConsumers(ctx context.Context, in *ListConsumersRequest, opts ...grpc.CallOption) (*ListConsumersResponse, error)
	Monitor(ctx context.Context, in *avpipeline.MonitorRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[avpipeline.MonitorEvent], error)
	SetPrivacyBlur(ctx context.Context, in *SetPrivacyBlurRequest, opts ...grpc.CallOption) (*SetPrivacyBlurResponse, error)
	GetPrivacyBlur(ctx context.Context, in *GetPrivacyBlurRequest, opts ...grpc.CallOption) (*GetPrivacyBlurResponse, error)
	SetDeblemish(ctx context.Context, in *SetDeblemishRequest, opts ...grpc.CallOption) (*SetDeblemishResponse, error)
	GetDeblemish(ctx context.Context, in *GetDeblemishRequest, opts ...grpc.CallOption) (*GetDeblemishResponse, error)
	ListFilterControls(ctx context.Context, in *ListFilterControlsRequest, opts ...grpc.CallOption) (*ListFilterControlsResponse, error)
}

type avdServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAvdServiceClient(cc grpc.ClientConnInterface) AvdServiceClient {
	return &avdServiceClient{cc}
}

func (c *avdServiceClient) ListPublishers(ctx context.Context, in *ListPublishersRequest, opts ...grpc.CallOption) (*ListPublishersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPublishersResponse)
	err := c.cc.Invoke(ctx, AvdService_ListPublishers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avdServiceClient) ListRoutes(ctx context.Context, in *ListRoutesRequest, opts ...grpc.CallOption) (*ListRoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoutesResponse)
	err := c.cc.Invoke(ctx, AvdService_ListRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avdServiceClient) ListConsumers(ctx context.Context, in *ListConsumersRequest, opts ...grpc.CallOption) (*ListConsumersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConsumersResponse)
	err := c.cc.Invoke(ctx, AvdService_ListConsumers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avdServiceClient) Monitor(ctx context.Context, in *avpipeline.MonitorRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[avpipeline.MonitorEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AvdService_ServiceDesc.Streams[0], AvdService_Monitor_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[avpipeline.MonitorRequest, avpipeline.MonitorEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AvdService_MonitorClient = grpc.ServerStreamingClient[avpipeline.MonitorEvent]

func (c *avdServiceClient) SetPrivacyBlur(ctx context.Context, in *SetPrivacyBlurRequest, opts ...grpc.CallOption) (*SetPrivacyBlurResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPrivacyBlurResponse)
	err := c.cc.Invoke(ctx, AvdService_SetPrivacyBlur_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avdServiceClient) GetPrivacyBlur(ctx context.Context, in *GetPrivacyBlurRequest, opts ...grpc.CallOption) (*GetPrivacyBlurResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPrivacyBlurResponse)
	err := c.cc.Invoke(ctx, AvdService_GetPrivacyBlur_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avdServiceClient) SetDeblemish(ctx context.Context, in *SetDeblemishRequest, opts ...grpc.CallOption) (*SetDeblemishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetDeblemishResponse)
	err := c.cc.Invoke(ctx, AvdService_SetDeblemish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avdServiceClient) GetDeblemish(ctx context.Context, in *GetDeblemishRequest, opts ...grpc.CallOption) (*GetDeblemishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeblemishResponse)
	err := c.cc.Invoke(ctx, AvdService_GetDeblemish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avdServiceClient) ListFilterControls(ctx context.Context, in *ListFilterControlsRequest, opts ...grpc.CallOption) (*ListFilterControlsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFilterControlsResponse)
	err := c.cc.Invoke(ctx, AvdService_ListFilterControls_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AvdServiceServer is the server API for AvdService service.
// All implementations must embed UnimplementedAvdServiceServer
// for forward compatibility.
type AvdServiceServer interface {
	ListPublishers(context.Context, *ListPublishersRequest) (*ListPublishersResponse, error)
	ListRoutes(context.Context, *ListRoutesRequest) (*ListRoutesResponse, error)
	ListConsumers(context.Context, *ListConsumersRequest) (*ListConsumersResponse, error)
	Monitor(*avpipeline.MonitorRequest, grpc.ServerStreamingServer[avpipeline.MonitorEvent]) error
	SetPrivacyBlur(context.Context, *SetPrivacyBlurRequest) (*SetPrivacyBlurResponse, error)
	GetPrivacyBlur(context.Context, *GetPrivacyBlurRequest) (*GetPrivacyBlurResponse, error)
	SetDeblemish(context.Context, *SetDeblemishRequest) (*SetDeblemishResponse, error)
	GetDeblemish(context.Context, *GetDeblemishRequest) (*GetDeblemishResponse, error)
	ListFilterControls(context.Context, *ListFilterControlsRequest) (*ListFilterControlsResponse, error)
	mustEmbedUnimplementedAvdServiceServer()
}

// UnimplementedAvdServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAvdServiceServer struct{}

func (UnimplementedAvdServiceServer) ListPublishers(context.Context, *ListPublishersRequest) (*ListPublishersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPublishers not implemented")
}
func (UnimplementedAvdServiceServer) ListRoutes(context.Context, *ListRoutesRequest) (*ListRoutesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRoutes not implemented")
}
func (UnimplementedAvdServiceServer) ListConsumers(context.Context, *ListConsumersRequest) (*ListConsumersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListConsumers not implemented")
}
func (UnimplementedAvdServiceServer) Monitor(*avpipeline.MonitorRequest, grpc.ServerStreamingServer[avpipeline.MonitorEvent]) error {
	return status.Error(codes.Unimplemented, "method Monitor not implemented")
}
func (UnimplementedAvdServiceServer) SetPrivacyBlur(context.Context, *SetPrivacyBlurRequest) (*SetPrivacyBlurResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPrivacyBlur not implemented")
}
func (UnimplementedAvdServiceServer) GetPrivacyBlur(context.Context, *GetPrivacyBlurRequest) (*GetPrivacyBlurResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPrivacyBlur not implemented")
}
func (UnimplementedAvdServiceServer) SetDeblemish(context.Context, *SetDeblemishRequest) (*SetDeblemishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDeblemish not implemented")
}
func (UnimplementedAvdServiceServer) GetDeblemish(context.Context, *GetDeblemishRequest) (*GetDeblemishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeblemish not implemented")
}
func (UnimplementedAvdServiceServer) ListFilterControls(context.Context, *ListFilterControlsRequest) (*ListFilterControlsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFilterControls not implemented")
}
func (UnimplementedAvdServiceServer) mustEmbedUnimplementedAvdServiceServer() {}
func (UnimplementedAvdServiceServer) testEmbeddedByValue()                    {}

// UnsafeAvdServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AvdServiceServer will
// result in compilation errors.
type UnsafeAvdServiceServer interface {
	mustEmbedUnimplementedAvdServiceServer()
}

func RegisterAvdServiceServer(s grpc.ServiceRegistrar, srv AvdServiceServer) {
	// If the following call panics, it indicates UnimplementedAvdServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AvdService_ServiceDesc, srv)
}

func _AvdService_ListPublishers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPublishersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvdServiceServer).ListPublishers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AvdService_ListPublishers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvdServiceServer).ListPublishers(ctx, req.(*ListPublishersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AvdService_ListRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvdServiceServer).ListRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AvdService_ListRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvdServiceServer).ListRoutes(ctx, req.(*ListRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AvdService_ListConsumers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConsumersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvdServiceServer).ListConsumers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AvdService_ListConsumers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvdServiceServer).ListConsumers(ctx, req.(*ListConsumersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AvdService_Monitor_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(avpipeline.MonitorRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AvdServiceServer).Monitor(m, &grpc.GenericServerStream[avpipeline.MonitorRequest, avpipeline.MonitorEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AvdService_MonitorServer = grpc.ServerStreamingServer[avpipeline.MonitorEvent]

func _AvdService_SetPrivacyBlur_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPrivacyBlurRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvdServiceServer).SetPrivacyBlur(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AvdService_SetPrivacyBlur_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvdServiceServer).SetPrivacyBlur(ctx, req.(*SetPrivacyBlurRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AvdService_GetPrivacyBlur_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPrivacyBlurRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvdServiceServer).GetPrivacyBlur(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AvdService_GetPrivacyBlur_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvdServiceServer).GetPrivacyBlur(ctx, req.(*GetPrivacyBlurRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AvdService_SetDeblemish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDeblemishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvdServiceServer).SetDeblemish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AvdService_SetDeblemish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvdServiceServer).SetDeblemish(ctx, req.(*SetDeblemishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AvdService_GetDeblemish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeblemishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvdServiceServer).GetDeblemish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AvdService_GetDeblemish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvdServiceServer).GetDeblemish(ctx, req.(*GetDeblemishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AvdService_ListFilterControls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFilterControlsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvdServiceServer).ListFilterControls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AvdService_ListFilterControls_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvdServiceServer).ListFilterControls(ctx, req.(*ListFilterControlsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AvdService_ServiceDesc is the grpc.ServiceDesc for AvdService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AvdService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AvdService",
	HandlerType: (*AvdServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPublishers",
			Handler:    _AvdService_ListPublishers_Handler,
		},
		{
			MethodName: "ListRoutes",
			Handler:    _AvdService_ListRoutes_Handler,
		},
		{
			MethodName: "ListConsumers",
			Handler:    _AvdService_ListConsumers_Handler,
		},
		{
			MethodName: "SetPrivacyBlur",
			Handler:    _AvdService_SetPrivacyBlur_Handler,
		},
		{
			MethodName: "GetPrivacyBlur",
			Handler:    _AvdService_GetPrivacyBlur_Handler,
		},
		{
			MethodName: "SetDeblemish",
			Handler:    _AvdService_SetDeblemish_Handler,
		},
		{
			MethodName: "GetDeblemish",
			Handler:    _AvdService_GetDeblemish_Handler,
		},
		{
			MethodName: "ListFilterControls",
			Handler:    _AvdService_ListFilterControls_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Monitor",
			Handler:       _AvdService_Monitor_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "avd.proto",
}
