// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: avd.proto

package avdmanagementgrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	AvdService_ListPublishers_FullMethodName = "/AvdService/ListPublishers"
	AvdService_ListConsumers_FullMethodName  = "/AvdService/ListConsumers"
)

// AvdServiceClient is the client API for AvdService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AvdServiceClient interface {
	ListPublishers(ctx context.Context, in *ListPublishersRequest, opts ...grpc.CallOption) (*ListPublishersResponse, error)
	ListConsumers(ctx context.Context, in *ListConsumersRequest, opts ...grpc.CallOption) (*ListConsumersResponse, error)
}

type avdServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAvdServiceClient(cc grpc.ClientConnInterface) AvdServiceClient {
	return &avdServiceClient{cc}
}

func (c *avdServiceClient) ListPublishers(ctx context.Context, in *ListPublishersRequest, opts ...grpc.CallOption) (*ListPublishersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPublishersResponse)
	err := c.cc.Invoke(ctx, AvdService_ListPublishers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avdServiceClient) ListConsumers(ctx context.Context, in *ListConsumersRequest, opts ...grpc.CallOption) (*ListConsumersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConsumersResponse)
	err := c.cc.Invoke(ctx, AvdService_ListConsumers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AvdServiceServer is the server API for AvdService service.
// All implementations must embed UnimplementedAvdServiceServer
// for forward compatibility
type AvdServiceServer interface {
	ListPublishers(context.Context, *ListPublishersRequest) (*ListPublishersResponse, error)
	ListConsumers(context.Context, *ListConsumersRequest) (*ListConsumersResponse, error)
	mustEmbedUnimplementedAvdServiceServer()
}

// UnimplementedAvdServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAvdServiceServer struct {
}

func (UnimplementedAvdServiceServer) ListPublishers(context.Context, *ListPublishersRequest) (*ListPublishersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPublishers not implemented")
}
func (UnimplementedAvdServiceServer) ListConsumers(context.Context, *ListConsumersRequest) (*ListConsumersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConsumers not implemented")
}
func (UnimplementedAvdServiceServer) mustEmbedUnimplementedAvdServiceServer() {}

// UnsafeAvdServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AvdServiceServer will
// result in compilation errors.
type UnsafeAvdServiceServer interface {
	mustEmbedUnimplementedAvdServiceServer()
}

func RegisterAvdServiceServer(s grpc.ServiceRegistrar, srv AvdServiceServer) {
	s.RegisterService(&AvdService_ServiceDesc, srv)
}

func _AvdService_ListPublishers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPublishersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvdServiceServer).ListPublishers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AvdService_ListPublishers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvdServiceServer).ListPublishers(ctx, req.(*ListPublishersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AvdService_ListConsumers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConsumersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvdServiceServer).ListConsumers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AvdService_ListConsumers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvdServiceServer).ListConsumers(ctx, req.(*ListConsumersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AvdService_ServiceDesc is the grpc.ServiceDesc for AvdService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AvdService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AvdService",
	HandlerType: (*AvdServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPublishers",
			Handler:    _AvdService_ListPublishers_Handler,
		},
		{
			MethodName: "ListConsumers",
			Handler:    _AvdService_ListConsumers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "avd.proto",
}
