// Tests auto-generated by AI agent.
package config

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"
)

func TestPrivacyBlurConfig_YAMLRoundTrip(t *testing.T) {
	cfg := PrivacyBlurConfig{
		Enabled:           true,
		Faces:             true,
		Plates:            true,
		BlurRadius:        15.5,
		PixelateBlockSize: 8,
	}

	data, err := yaml.Marshal(cfg)
	require.NoError(t, err)

	var got PrivacyBlurConfig
	require.NoError(t, yaml.Unmarshal(data, &got))

	assert.Equal(t, cfg, got)
}

func TestPrivacyBlurConfig_YAMLParse(t *testing.T) {
	yamlData := `
enabled: true
faces: true
plates: false
blur_radius: 20
pixelate_block_size: 10
`
	var cfg PrivacyBlurConfig
	require.NoError(t, yaml.Unmarshal([]byte(yamlData), &cfg))

	assert.True(t, cfg.Enabled)
	assert.True(t, cfg.Faces)
	assert.False(t, cfg.Plates)
	assert.Equal(t, float64(20), cfg.BlurRadius)
	assert.Equal(t, 10, cfg.PixelateBlockSize)
}

func TestPrivacyBlurConfig_Defaults(t *testing.T) {
	var cfg PrivacyBlurConfig
	require.NoError(t, yaml.Unmarshal([]byte("{}"), &cfg))

	assert.False(t, cfg.Enabled)
	assert.False(t, cfg.Faces)
	assert.False(t, cfg.Plates)
	assert.Equal(t, float64(0), cfg.BlurRadius)
	assert.Equal(t, 0, cfg.PixelateBlockSize)
}

func TestForwardConfig_WithPrivacyBlur(t *testing.T) {
	yamlData := `
destination:
  url: "rtmp://example.com/live/stream"
privacy_blur:
  enabled: true
  faces: true
  blur_radius: 15
`
	var cfg ForwardConfig
	require.NoError(t, yaml.Unmarshal([]byte(yamlData), &cfg))

	require.NotNil(t, cfg.PrivacyBlur)
	assert.True(t, cfg.PrivacyBlur.Enabled)
	assert.True(t, cfg.PrivacyBlur.Faces)
	assert.Equal(t, float64(15), cfg.PrivacyBlur.BlurRadius)
}

func TestForwardConfig_WithoutPrivacyBlur(t *testing.T) {
	yamlData := `
destination:
  url: "rtmp://example.com/live/stream"
`
	var cfg ForwardConfig
	require.NoError(t, yaml.Unmarshal([]byte(yamlData), &cfg))

	assert.Nil(t, cfg.PrivacyBlur, "privacy_blur should be nil when omitted")
}

func TestForwardConfig_PrivacyBlurOmittedInOutput(t *testing.T) {
	cfg := ForwardConfig{
		Destination: Destination{},
	}

	data, err := yaml.Marshal(cfg)
	require.NoError(t, err)
	assert.NotContains(t, string(data), "privacy_blur",
		"omitempty should suppress privacy_blur when nil")
}

func TestPrivacyBlurConfig_InFullConfig(t *testing.T) {
	yamlData := `
endpoints:
  /live:
    forwardings:
      - destination:
          url: "rtmp://example.com/live/stream"
        privacy_blur:
          enabled: true
          faces: true
          plates: true
          blur_radius: 25
`
	var buf bytes.Buffer
	buf.WriteString(yamlData)
	var cfg Config
	_, err := cfg.ReadFrom(&buf)
	require.NoError(t, err)

	ep, ok := cfg.Endpoints["/live"]
	require.True(t, ok)
	require.Len(t, ep.Forwardings, 1)
	require.NotNil(t, ep.Forwardings[0].PrivacyBlur)
	assert.True(t, ep.Forwardings[0].PrivacyBlur.Enabled)
	assert.True(t, ep.Forwardings[0].PrivacyBlur.Faces)
	assert.True(t, ep.Forwardings[0].PrivacyBlur.Plates)
	assert.Equal(t, float64(25), ep.Forwardings[0].PrivacyBlur.BlurRadius)
}
