// Tests auto-generated by AI agent.
package configapplier

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/xaionaro-go/avd/pkg/config"
)

func TestNewDeblemishFactory_NilConfig(t *testing.T) {
	factory, control := newDeblemishFactory(nil)
	assert.Nil(t, factory, "nil config should produce nil factory")
	assert.Nil(t, control, "nil config should produce nil control")
}

func TestNewDeblemishFactory_DisabledPassthrough(t *testing.T) {
	cfg := &config.DeblemishConfig{Enabled: false, SigmaS: 10.0, SigmaR: 0.1}
	factory, control := newDeblemishFactory(cfg)
	// Passthrough: factory and control created so avcli can enable at runtime.
	require.NotNil(t, factory, "disabled config should still produce a factory for runtime enable")
	require.NotNil(t, control, "disabled config should still produce a control for runtime enable")
	assert.False(t, control.Enabled.Load(), "Enabled should be false in passthrough mode")
	assert.Equal(t, 10.0, control.GetSigmaS(), "SigmaS should be set from config")
	assert.Equal(t, 0.1, control.GetSigmaR(), "SigmaR should be set from config")
}

func TestNewDeblemishFactory_Enabled(t *testing.T) {
	cfg := &config.DeblemishConfig{
		Enabled:  true,
		SigmaS:   15.0,
		SigmaR:   0.2,
		Diameter: 5,
	}
	factory, control := newDeblemishFactory(cfg)
	require.NotNil(t, factory, "enabled config should produce a factory")
	require.NotNil(t, control, "enabled config should produce a control")
	assert.True(t, control.Enabled.Load(), "Enabled should be true")
	assert.Equal(t, 15.0, control.GetSigmaS())
	assert.Equal(t, 0.2, control.GetSigmaR())
	assert.Equal(t, int64(5), control.Diameter.Load())
}
