syntax = "proto3";
import "imports/avpipeline/protobuf/avpipeline.proto";

option go_package = "github.com/xaionaro-go/avd/pkg/management/grpc/proto;avdmanagementgrpc";

service AvdService {
    rpc ListPublishers (ListPublishersRequest) returns (ListPublisherResponse);
    rpc ListConsumers (ListConsumersRequest) returns (ListConsumersResponse);
}

message ListPublishersRequest {}
message ListPublisherResponse {
    repeated avpipeline.Node nodes = 1;
}

message ListConsumersRequest {}
message ListConsumersResponse {
    repeated avpipeline.Node nodes = 1;
}

